name: CI

on:
  push:
    branches: [master]
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Test
        run: cargo test
          
      - name: Serde check
        run: cargo check --features="serde_serialization"

      - name: Num traits check
        run: cargo check --features="num_traits"

  build_result:
    name: Result
    runs-on: ubuntu-latest
    needs:
      - "Test"
    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
